/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-23 18:35:03 UTC)
 * on 2013-10-28 at 09:45:57 UTC 
 * Modify at your own risk.
 */

package edu.vt.bmac.gpstracker.nodeendpoint;

/**
 * Service definition for Nodeendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link NodeendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Nodeendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the nodeendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://gpstracker-bmac.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "nodeendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Nodeendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Nodeendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getNode".
   *
   * This request holds the parameters needed by the the nodeendpoint server.  After setting any
   * optional parameters, call the {@link GetNode#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetNode getNode(java.lang.Long id) throws java.io.IOException {
    GetNode result = new GetNode(id);
    initialize(result);
    return result;
  }

  public class GetNode extends NodeendpointRequest<edu.vt.bmac.gpstracker.nodeendpoint.model.Node> {

    private static final String REST_PATH = "node/{id}";

    /**
     * Create a request for the method "getNode".
     *
     * This request holds the parameters needed by the the nodeendpoint server.  After setting any
     * optional parameters, call the {@link GetNode#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetNode#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetNode(java.lang.Long id) {
      super(Nodeendpoint.this, "GET", REST_PATH, null, edu.vt.bmac.gpstracker.nodeendpoint.model.Node.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetNode setAlt(java.lang.String alt) {
      return (GetNode) super.setAlt(alt);
    }

    @Override
    public GetNode setFields(java.lang.String fields) {
      return (GetNode) super.setFields(fields);
    }

    @Override
    public GetNode setKey(java.lang.String key) {
      return (GetNode) super.setKey(key);
    }

    @Override
    public GetNode setOauthToken(java.lang.String oauthToken) {
      return (GetNode) super.setOauthToken(oauthToken);
    }

    @Override
    public GetNode setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetNode) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetNode setQuotaUser(java.lang.String quotaUser) {
      return (GetNode) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetNode setUserIp(java.lang.String userIp) {
      return (GetNode) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetNode setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetNode set(String parameterName, Object value) {
      return (GetNode) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertNode".
   *
   * This request holds the parameters needed by the the nodeendpoint server.  After setting any
   * optional parameters, call the {@link InsertNode#execute()} method to invoke the remote operation.
   *
   * @param content the {@link edu.vt.bmac.gpstracker.nodeendpoint.model.Node}
   * @return the request
   */
  public InsertNode insertNode(edu.vt.bmac.gpstracker.nodeendpoint.model.Node content) throws java.io.IOException {
    InsertNode result = new InsertNode(content);
    initialize(result);
    return result;
  }

  public class InsertNode extends NodeendpointRequest<edu.vt.bmac.gpstracker.nodeendpoint.model.Node> {

    private static final String REST_PATH = "node";

    /**
     * Create a request for the method "insertNode".
     *
     * This request holds the parameters needed by the the nodeendpoint server.  After setting any
     * optional parameters, call the {@link InsertNode#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertNode#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link edu.vt.bmac.gpstracker.nodeendpoint.model.Node}
     * @since 1.13
     */
    protected InsertNode(edu.vt.bmac.gpstracker.nodeendpoint.model.Node content) {
      super(Nodeendpoint.this, "POST", REST_PATH, content, edu.vt.bmac.gpstracker.nodeendpoint.model.Node.class);
    }

    @Override
    public InsertNode setAlt(java.lang.String alt) {
      return (InsertNode) super.setAlt(alt);
    }

    @Override
    public InsertNode setFields(java.lang.String fields) {
      return (InsertNode) super.setFields(fields);
    }

    @Override
    public InsertNode setKey(java.lang.String key) {
      return (InsertNode) super.setKey(key);
    }

    @Override
    public InsertNode setOauthToken(java.lang.String oauthToken) {
      return (InsertNode) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertNode setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertNode) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertNode setQuotaUser(java.lang.String quotaUser) {
      return (InsertNode) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertNode setUserIp(java.lang.String userIp) {
      return (InsertNode) super.setUserIp(userIp);
    }

    @Override
    public InsertNode set(String parameterName, Object value) {
      return (InsertNode) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listNode".
   *
   * This request holds the parameters needed by the the nodeendpoint server.  After setting any
   * optional parameters, call the {@link ListNode#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListNode listNode() throws java.io.IOException {
    ListNode result = new ListNode();
    initialize(result);
    return result;
  }

  public class ListNode extends NodeendpointRequest<edu.vt.bmac.gpstracker.nodeendpoint.model.CollectionResponseNode> {

    private static final String REST_PATH = "node";

    /**
     * Create a request for the method "listNode".
     *
     * This request holds the parameters needed by the the nodeendpoint server.  After setting any
     * optional parameters, call the {@link ListNode#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListNode#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListNode() {
      super(Nodeendpoint.this, "GET", REST_PATH, null, edu.vt.bmac.gpstracker.nodeendpoint.model.CollectionResponseNode.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListNode setAlt(java.lang.String alt) {
      return (ListNode) super.setAlt(alt);
    }

    @Override
    public ListNode setFields(java.lang.String fields) {
      return (ListNode) super.setFields(fields);
    }

    @Override
    public ListNode setKey(java.lang.String key) {
      return (ListNode) super.setKey(key);
    }

    @Override
    public ListNode setOauthToken(java.lang.String oauthToken) {
      return (ListNode) super.setOauthToken(oauthToken);
    }

    @Override
    public ListNode setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListNode) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListNode setQuotaUser(java.lang.String quotaUser) {
      return (ListNode) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListNode setUserIp(java.lang.String userIp) {
      return (ListNode) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListNode setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListNode setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListNode set(String parameterName, Object value) {
      return (ListNode) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeNode".
   *
   * This request holds the parameters needed by the the nodeendpoint server.  After setting any
   * optional parameters, call the {@link RemoveNode#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveNode removeNode(java.lang.Long id) throws java.io.IOException {
    RemoveNode result = new RemoveNode(id);
    initialize(result);
    return result;
  }

  public class RemoveNode extends NodeendpointRequest<Void> {

    private static final String REST_PATH = "node/{id}";

    /**
     * Create a request for the method "removeNode".
     *
     * This request holds the parameters needed by the the nodeendpoint server.  After setting any
     * optional parameters, call the {@link RemoveNode#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveNode#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveNode(java.lang.Long id) {
      super(Nodeendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveNode setAlt(java.lang.String alt) {
      return (RemoveNode) super.setAlt(alt);
    }

    @Override
    public RemoveNode setFields(java.lang.String fields) {
      return (RemoveNode) super.setFields(fields);
    }

    @Override
    public RemoveNode setKey(java.lang.String key) {
      return (RemoveNode) super.setKey(key);
    }

    @Override
    public RemoveNode setOauthToken(java.lang.String oauthToken) {
      return (RemoveNode) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveNode setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveNode) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveNode setQuotaUser(java.lang.String quotaUser) {
      return (RemoveNode) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveNode setUserIp(java.lang.String userIp) {
      return (RemoveNode) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveNode setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveNode set(String parameterName, Object value) {
      return (RemoveNode) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateNode".
   *
   * This request holds the parameters needed by the the nodeendpoint server.  After setting any
   * optional parameters, call the {@link UpdateNode#execute()} method to invoke the remote operation.
   *
   * @param content the {@link edu.vt.bmac.gpstracker.nodeendpoint.model.Node}
   * @return the request
   */
  public UpdateNode updateNode(edu.vt.bmac.gpstracker.nodeendpoint.model.Node content) throws java.io.IOException {
    UpdateNode result = new UpdateNode(content);
    initialize(result);
    return result;
  }

  public class UpdateNode extends NodeendpointRequest<edu.vt.bmac.gpstracker.nodeendpoint.model.Node> {

    private static final String REST_PATH = "node";

    /**
     * Create a request for the method "updateNode".
     *
     * This request holds the parameters needed by the the nodeendpoint server.  After setting any
     * optional parameters, call the {@link UpdateNode#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateNode#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link edu.vt.bmac.gpstracker.nodeendpoint.model.Node}
     * @since 1.13
     */
    protected UpdateNode(edu.vt.bmac.gpstracker.nodeendpoint.model.Node content) {
      super(Nodeendpoint.this, "PUT", REST_PATH, content, edu.vt.bmac.gpstracker.nodeendpoint.model.Node.class);
    }

    @Override
    public UpdateNode setAlt(java.lang.String alt) {
      return (UpdateNode) super.setAlt(alt);
    }

    @Override
    public UpdateNode setFields(java.lang.String fields) {
      return (UpdateNode) super.setFields(fields);
    }

    @Override
    public UpdateNode setKey(java.lang.String key) {
      return (UpdateNode) super.setKey(key);
    }

    @Override
    public UpdateNode setOauthToken(java.lang.String oauthToken) {
      return (UpdateNode) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateNode setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateNode) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateNode setQuotaUser(java.lang.String quotaUser) {
      return (UpdateNode) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateNode setUserIp(java.lang.String userIp) {
      return (UpdateNode) super.setUserIp(userIp);
    }

    @Override
    public UpdateNode set(String parameterName, Object value) {
      return (UpdateNode) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Nodeendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Nodeendpoint}. */
    @Override
    public Nodeendpoint build() {
      return new Nodeendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link NodeendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setNodeendpointRequestInitializer(
        NodeendpointRequestInitializer nodeendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(nodeendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
