/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-23 18:35:03 UTC)
 * on 2013-10-28 at 02:14:01 UTC 
 * Modify at your own risk.
 */

package edu.vt.bmac.gpstracker.trailendpoint.model;

/**
 * Model definition for Trail.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the trailendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Trail extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String alt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String dist;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long hash;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Node> plots;

  static {
    // hack to force ProGuard to consider Node used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Node.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String speed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String time;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String username;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAlt() {
    return alt;
  }

  /**
   * @param alt alt or {@code null} for none
   */
  public Trail setAlt(java.lang.String alt) {
    this.alt = alt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDist() {
    return dist;
  }

  /**
   * @param dist dist or {@code null} for none
   */
  public Trail setDist(java.lang.String dist) {
    this.dist = dist;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getHash() {
    return hash;
  }

  /**
   * @param hash hash or {@code null} for none
   */
  public Trail setHash(java.lang.Long hash) {
    this.hash = hash;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Trail setId(java.lang.Integer id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Trail setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Node> getPlots() {
    return plots;
  }

  /**
   * @param plots plots or {@code null} for none
   */
  public Trail setPlots(java.util.List<Node> plots) {
    this.plots = plots;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSpeed() {
    return speed;
  }

  /**
   * @param speed speed or {@code null} for none
   */
  public Trail setSpeed(java.lang.String speed) {
    this.speed = speed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTime() {
    return time;
  }

  /**
   * @param time time or {@code null} for none
   */
  public Trail setTime(java.lang.String time) {
    this.time = time;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUsername() {
    return username;
  }

  /**
   * @param username username or {@code null} for none
   */
  public Trail setUsername(java.lang.String username) {
    this.username = username;
    return this;
  }

  @Override
  public Trail set(String fieldName, Object value) {
    return (Trail) super.set(fieldName, value);
  }

  @Override
  public Trail clone() {
    return (Trail) super.clone();
  }

}
